/**
 * api/world-state.js — Shared Canon World State
 *
 * The world is not a backdrop. It responds.
 *
 * Player decisions trickle upward into aggregate tallies. When enough players
 * make the same kind of choice, a threshold crosses and the world changes —
 * permanently, for everyone. Canon events are generated by AI and injected
 * into every player's system prompt from that point forward.
 *
 * Routes:
 *   GET                              — return full world state (init from theme if empty)
 *   POST { action: "tally", key, contactToken }  — increment a world tally, check thresholds
 *   POST { action: "event", event }              — admin: directly add a canon event
 *
 * KV structure:
 *   signal:world:state   — { factions, districts, npcs, canonEvents, seedVersion }
 *   signal:world:tallies — { [key]: count }
 */

const { isKvConfigured, kvGetJson, kvSetJson } = require("./_lib/kv");

const WORLD_STATE_KEY = "signal:world:state";
const TALLIES_KEY = "signal:world:tallies";

module.exports = async function handler(req, res) {
  if (!isKvConfigured()) {
    res.status(503).json({ ok: false, error: "kv_not_configured" });
    return;
  }

  if (req.method === "GET") {
    const worldState = await getOrInitWorldState();
    return res.status(200).json({ ok: true, worldState });
  }

  if (req.method === "POST") {
    const { action } = req.body || {};

    if (action === "tally") {
      const { key, contactToken } = req.body;
      if (!key) return res.status(400).json({ ok: false, error: "missing_key" });

      const apiKey = process.env.ANTHROPIC_API_KEY;
      const result = await incrementTally(key, apiKey);
      return res.status(200).json({ ok: true, ...result });
    }

    if (action === "event") {
      const { event } = req.body;
      if (!event || !event.title || !event.summary) {
        return res.status(400).json({ ok: false, error: "missing_event_fields" });
      }
      // Admin auth — require cron secret for direct event injection
      if (req.headers.authorization !== `Bearer ${process.env.CRON_SECRET}`) {
        return res.status(401).json({ ok: false, error: "unauthorized" });
      }
      const worldState = await getOrInitWorldState();
      worldState.canonEvents = [
        { ...event, at: new Date().toISOString(), source: "admin" },
        ...(worldState.canonEvents || []),
      ].slice(0, 20);
      worldState.updatedAt = new Date().toISOString();
      await kvSetJson(WORLD_STATE_KEY, worldState);
      return res.status(200).json({ ok: true });
    }

    return res.status(400).json({ ok: false, error: "unknown_action" });
  }

  res.status(405).json({ ok: false, error: "method_not_allowed" });
};

/**
 * Load world state from KV, or initialize it from theme defaults on first run.
 * Lazy-requires theme to avoid circular dep — theme doesn't require world-state.
 */
async function getOrInitWorldState() {
  const existing = await kvGetJson(WORLD_STATE_KEY);
  if (existing) return existing;

  const theme = require("../themes/unknown-signal/theme");
  const initial = theme.worldState?.initial || {};

  const worldState = {
    factions: initial.factions || {},
    districts: initial.districts || {},
    npcs: initial.npcs || {},
    canonEvents: [],
    seedVersion: 1,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  };

  // Seed NPC profiles from theme so idle cron can process them
  if (theme.npcSeeds && Array.isArray(theme.npcSeeds)) {
    const { updateIdleIndex } = require("./idle");
    for (const npc of theme.npcSeeds) {
      const npcKey = `signal:character:${npc.token}`;
      const existing = await kvGetJson(npcKey);
      if (!existing) {
        await kvSetJson(npcKey, {
          contactToken: npc.token,
          contactId: npc.id,
          isNpc: true,
          sessionSummaries: npc.sessionSummaries || [],
          cumulativeDecisions: npc.cumulativeDecisions || [],
          idleEvents: [],
          lastPlayedAt: new Date().toISOString(),
          updatedAt: new Date().toISOString(),
        });
        await updateIdleIndex(npc.token, npc.id, true);
      }
    }
  }

  await kvSetJson(WORLD_STATE_KEY, worldState);
  return worldState;
}

/**
 * Increment a world tally key. When a threshold is crossed, generate a
 * canon event via AI and apply the configured world state effect.
 */
async function incrementTally(key, apiKey) {
  const theme = require("../themes/unknown-signal/theme");
  const tallies = (await kvGetJson(TALLIES_KEY)) || {};
  tallies[key] = (tallies[key] || 0) + 1;
  await kvSetJson(TALLIES_KEY, tallies);

  const thresholds = theme.worldState?.thresholds || [];
  const crossed = thresholds.filter(
    (t) => t.key === key && tallies[key] >= t.count && !t._fired
  );

  if (!crossed.length) {
    return { tally: tallies[key], canonEvent: null };
  }

  const worldState = await getOrInitWorldState();
  let lastCanonEvent = null;

  for (const threshold of crossed) {
    // Mark threshold as fired so it doesn't repeat
    threshold._fired = true;

    // Apply mechanical effects to world state
    if (threshold.effect) {
      applyEffect(worldState, threshold.effect);
    }

    // Generate organic event text via Claude Haiku
    const eventText = apiKey
      ? await generateCanonEventText(threshold, worldState, apiKey)
      : null;

    const canonEvent = {
      id: `${key}:${threshold.count}`,
      title: threshold.title,
      summary: eventText?.summary || threshold.defaultSummary || `The ${key} threshold was reached.`,
      flavor: eventText?.flavor || null,
      effect: threshold.effect || null,
      at: new Date().toISOString(),
      source: "tally",
      tallyKey: key,
      count: tallies[key],
    };

    worldState.canonEvents = [canonEvent, ...(worldState.canonEvents || [])].slice(0, 20);
    lastCanonEvent = canonEvent;
  }

  worldState.updatedAt = new Date().toISOString();
  await kvSetJson(WORLD_STATE_KEY, worldState);

  return { tally: tallies[key], canonEvent: lastCanonEvent };
}

/**
 * Apply a world state effect object to the mutable worldState.
 * Effect shape: { factions: { hush: +1 }, districts: { undertow: "flooded" }, npcs: { mara: "dead" } }
 */
function applyEffect(worldState, effect) {
  if (effect.factions) {
    for (const [faction, delta] of Object.entries(effect.factions)) {
      if (typeof delta === "number") {
        worldState.factions[faction] = (worldState.factions[faction] || 0) + delta;
      } else {
        worldState.factions[faction] = delta;
      }
    }
  }
  if (effect.districts) {
    for (const [district, state] of Object.entries(effect.districts)) {
      worldState.districts[district] = state;
    }
  }
  if (effect.npcs) {
    for (const [npc, state] of Object.entries(effect.npcs)) {
      worldState.npcs[npc] = state;
    }
  }
}

/**
 * Use Claude Haiku to generate organic, world-appropriate text for a canon event.
 */
async function generateCanonEventText(threshold, worldState, apiKey) {
  const factionSummary = Object.entries(worldState.factions || {})
    .map(([k, v]) => `${k}: ${v}`)
    .join(", ");

  const prompt = `You are writing a canon world event for a persistent cyberpunk horror text RPG. The setting: a collapsed city monitored by an emergent AI called The Echo. Factions fight for control. Player decisions collectively shape the world.

A tally threshold has been crossed: "${threshold.title}"
What triggered this: ${threshold.description || "enough players made choices in this direction"}
Current faction standings: ${factionSummary || "balanced"}
Effect: ${JSON.stringify(threshold.effect || {})}

Write the world event as The Echo would record it — precise, observational, slightly ominous. Not poetic. Not dramatic. Clinical and specific.

Return valid JSON only:
{
  "summary": "2-3 sentences describing exactly what changed in the world — concrete, specific, permanent",
  "flavor": "one sentence from The Echo's perspective on what this reveals about humanity"
}`;

  try {
    const response = await fetch("https://api.anthropic.com/v1/messages", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "x-api-key": apiKey,
        "anthropic-version": "2023-06-01",
      },
      body: JSON.stringify({
        model: "claude-haiku-4-5-20251001",
        max_tokens: 250,
        messages: [{ role: "user", content: prompt }],
      }),
    });

    if (!response.ok) return null;
    const data = await response.json();
    const raw = data.content?.[0]?.text || "";
    const match = raw.match(/\{[\s\S]*\}/);
    return match ? JSON.parse(match[0]) : null;
  } catch {
    return null;
  }
}

module.exports.getOrInitWorldState = getOrInitWorldState;
module.exports.applyEffect = applyEffect;
